### PR TITLE
MODLD-603: Intermittent failure fix

### PR DESCRIPTION
**Pull request by AndreiBordak**

### CODE REVIEW

**Comment by askhat-abishev** [comment]
could you check Sonar
you have an issue

**Comment by AndreiBordak** [comment]
> could you check Sonar you have an issue

done.

**Comment by askhat-abishev** [comment]
@AndreiBordak could you please check the ```Ld2MarcMapperIT.map_shouldMapDateFieldCorrectly```? It's failing on my machine

**Comment by askhat-abishev** [comment]
> @AndreiBordak could you please check the `Ld2MarcMapperIT.map_shouldMapDateFieldCorrectly`? It's failing on my machine

btw, not only on my local machine https://jenkins-aws.indexdata.com/job/folio-org/job/lib-linked-data-marc4ld/job/master/24/

**Review by askhat-abishev — APPROVED** [review]

**Pull request merged**
